version: "2"
linters:
  enable:
    - exhaustive
    - goconst
    - godox
    - misspell
    - mnd
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - examples
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - examples
